export const EXPORT_COLUMNS = [
  "product_id",
  "store_id",
  "external_id",
  "name",
  "name_ua",
  "vendor",
  "article",
  "docket",
  "docket_ua",
  "description",
  "description_ua",
  "currency_code",
  "currency_id",
  "price",
  "price_old",
  "price_promo",
  "stock_quantity",
  "available",
  "state",
  "category_id",
  "category_external_id",
  "supplier_id",
  "is_active",
  "created_at",
  "updated_at",
  "linked_store_ids",
  "images",
  "params",
] as const;

export type ExportColumn = typeof EXPORT_COLUMNS[number];
